// +build !ignore_autogenerated

/*
Copyright 2017 The Gardener Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	unsafe "unsafe"

	componentconfig "github.com/gardener/gardenctl/pkg/apis/componentconfig"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_ClientConnectionConfiguration_To_componentconfig_ClientConnectionConfiguration,
		Convert_componentconfig_ClientConnectionConfiguration_To_v1alpha1_ClientConnectionConfiguration,
		Convert_v1alpha1_ControllerReconciliationConfiguration_To_componentconfig_ControllerReconciliationConfiguration,
		Convert_componentconfig_ControllerReconciliationConfiguration_To_v1alpha1_ControllerReconciliationConfiguration,
		Convert_v1alpha1_GardenConstraints_To_componentconfig_GardenConstraints,
		Convert_componentconfig_GardenConstraints_To_v1alpha1_GardenConstraints,
		Convert_v1alpha1_GardenOperatorCloudProviderConfiguration_To_componentconfig_GardenOperatorCloudProviderConfiguration,
		Convert_componentconfig_GardenOperatorCloudProviderConfiguration_To_v1alpha1_GardenOperatorCloudProviderConfiguration,
		Convert_v1alpha1_GardenOperatorConfiguration_To_componentconfig_GardenOperatorConfiguration,
		Convert_componentconfig_GardenOperatorConfiguration_To_v1alpha1_GardenOperatorConfiguration,
		Convert_v1alpha1_GardenOperatorControllerConfiguration_To_componentconfig_GardenOperatorControllerConfiguration,
		Convert_componentconfig_GardenOperatorControllerConfiguration_To_v1alpha1_GardenOperatorControllerConfiguration,
		Convert_v1alpha1_GardenOperatorImagesConfiguration_To_componentconfig_GardenOperatorImagesConfiguration,
		Convert_componentconfig_GardenOperatorImagesConfiguration_To_v1alpha1_GardenOperatorImagesConfiguration,
		Convert_v1alpha1_LeaderElectionConfiguration_To_componentconfig_LeaderElectionConfiguration,
		Convert_componentconfig_LeaderElectionConfiguration_To_v1alpha1_LeaderElectionConfiguration,
		Convert_v1alpha1_ServerConfiguration_To_componentconfig_ServerConfiguration,
		Convert_componentconfig_ServerConfiguration_To_v1alpha1_ServerConfiguration,
	)
}

func autoConvert_v1alpha1_ClientConnectionConfiguration_To_componentconfig_ClientConnectionConfiguration(in *ClientConnectionConfiguration, out *componentconfig.ClientConnectionConfiguration, s conversion.Scope) error {
	out.KubeConfigFile = in.KubeConfigFile
	out.AcceptContentTypes = in.AcceptContentTypes
	out.ContentType = in.ContentType
	out.QPS = in.QPS
	out.Burst = in.Burst
	return nil
}

// Convert_v1alpha1_ClientConnectionConfiguration_To_componentconfig_ClientConnectionConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ClientConnectionConfiguration_To_componentconfig_ClientConnectionConfiguration(in *ClientConnectionConfiguration, out *componentconfig.ClientConnectionConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClientConnectionConfiguration_To_componentconfig_ClientConnectionConfiguration(in, out, s)
}

func autoConvert_componentconfig_ClientConnectionConfiguration_To_v1alpha1_ClientConnectionConfiguration(in *componentconfig.ClientConnectionConfiguration, out *ClientConnectionConfiguration, s conversion.Scope) error {
	out.KubeConfigFile = in.KubeConfigFile
	out.AcceptContentTypes = in.AcceptContentTypes
	out.ContentType = in.ContentType
	out.QPS = in.QPS
	out.Burst = in.Burst
	return nil
}

// Convert_componentconfig_ClientConnectionConfiguration_To_v1alpha1_ClientConnectionConfiguration is an autogenerated conversion function.
func Convert_componentconfig_ClientConnectionConfiguration_To_v1alpha1_ClientConnectionConfiguration(in *componentconfig.ClientConnectionConfiguration, out *ClientConnectionConfiguration, s conversion.Scope) error {
	return autoConvert_componentconfig_ClientConnectionConfiguration_To_v1alpha1_ClientConnectionConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ControllerReconciliationConfiguration_To_componentconfig_ControllerReconciliationConfiguration(in *ControllerReconciliationConfiguration, out *componentconfig.ControllerReconciliationConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = in.ConcurrentSyncs
	out.ResyncPeriod = in.ResyncPeriod
	if err := v1.Convert_Pointer_v1_Duration_To_v1_Duration(&in.RetryDuration, &out.RetryDuration, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ControllerReconciliationConfiguration_To_componentconfig_ControllerReconciliationConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ControllerReconciliationConfiguration_To_componentconfig_ControllerReconciliationConfiguration(in *ControllerReconciliationConfiguration, out *componentconfig.ControllerReconciliationConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControllerReconciliationConfiguration_To_componentconfig_ControllerReconciliationConfiguration(in, out, s)
}

func autoConvert_componentconfig_ControllerReconciliationConfiguration_To_v1alpha1_ControllerReconciliationConfiguration(in *componentconfig.ControllerReconciliationConfiguration, out *ControllerReconciliationConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = in.ConcurrentSyncs
	out.ResyncPeriod = in.ResyncPeriod
	if err := v1.Convert_v1_Duration_To_Pointer_v1_Duration(&in.RetryDuration, &out.RetryDuration, s); err != nil {
		return err
	}
	return nil
}

// Convert_componentconfig_ControllerReconciliationConfiguration_To_v1alpha1_ControllerReconciliationConfiguration is an autogenerated conversion function.
func Convert_componentconfig_ControllerReconciliationConfiguration_To_v1alpha1_ControllerReconciliationConfiguration(in *componentconfig.ControllerReconciliationConfiguration, out *ControllerReconciliationConfiguration, s conversion.Scope) error {
	return autoConvert_componentconfig_ControllerReconciliationConfiguration_To_v1alpha1_ControllerReconciliationConfiguration(in, out, s)
}

func autoConvert_v1alpha1_GardenConstraints_To_componentconfig_GardenConstraints(in *GardenConstraints, out *componentconfig.GardenConstraints, s conversion.Scope) error {
	out.CloudProviders = *(*[]componentconfig.GardenOperatorCloudProviderConfiguration)(unsafe.Pointer(&in.CloudProviders))
	out.KubernetesVersions = *(*[]string)(unsafe.Pointer(&in.KubernetesVersions))
	out.DNSProviders = *(*[]string)(unsafe.Pointer(&in.DNSProviders))
	return nil
}

// Convert_v1alpha1_GardenConstraints_To_componentconfig_GardenConstraints is an autogenerated conversion function.
func Convert_v1alpha1_GardenConstraints_To_componentconfig_GardenConstraints(in *GardenConstraints, out *componentconfig.GardenConstraints, s conversion.Scope) error {
	return autoConvert_v1alpha1_GardenConstraints_To_componentconfig_GardenConstraints(in, out, s)
}

func autoConvert_componentconfig_GardenConstraints_To_v1alpha1_GardenConstraints(in *componentconfig.GardenConstraints, out *GardenConstraints, s conversion.Scope) error {
	out.CloudProviders = *(*[]GardenOperatorCloudProviderConfiguration)(unsafe.Pointer(&in.CloudProviders))
	out.KubernetesVersions = *(*[]string)(unsafe.Pointer(&in.KubernetesVersions))
	out.DNSProviders = *(*[]string)(unsafe.Pointer(&in.DNSProviders))
	return nil
}

// Convert_componentconfig_GardenConstraints_To_v1alpha1_GardenConstraints is an autogenerated conversion function.
func Convert_componentconfig_GardenConstraints_To_v1alpha1_GardenConstraints(in *componentconfig.GardenConstraints, out *GardenConstraints, s conversion.Scope) error {
	return autoConvert_componentconfig_GardenConstraints_To_v1alpha1_GardenConstraints(in, out, s)
}

func autoConvert_v1alpha1_GardenOperatorCloudProviderConfiguration_To_componentconfig_GardenOperatorCloudProviderConfiguration(in *GardenOperatorCloudProviderConfiguration, out *componentconfig.GardenOperatorCloudProviderConfiguration, s conversion.Scope) error {
	out.Name = in.Name
	out.VolumeTypes = *(*[]string)(unsafe.Pointer(&in.VolumeTypes))
	out.MachineTypes = *(*[]string)(unsafe.Pointer(&in.MachineTypes))
	out.RootCerts = in.RootCerts
	out.LoadBalancerProvider = in.LoadBalancerProvider
	out.FloatingPoolName = in.FloatingPoolName
	return nil
}

// Convert_v1alpha1_GardenOperatorCloudProviderConfiguration_To_componentconfig_GardenOperatorCloudProviderConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_GardenOperatorCloudProviderConfiguration_To_componentconfig_GardenOperatorCloudProviderConfiguration(in *GardenOperatorCloudProviderConfiguration, out *componentconfig.GardenOperatorCloudProviderConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_GardenOperatorCloudProviderConfiguration_To_componentconfig_GardenOperatorCloudProviderConfiguration(in, out, s)
}

func autoConvert_componentconfig_GardenOperatorCloudProviderConfiguration_To_v1alpha1_GardenOperatorCloudProviderConfiguration(in *componentconfig.GardenOperatorCloudProviderConfiguration, out *GardenOperatorCloudProviderConfiguration, s conversion.Scope) error {
	out.Name = in.Name
	out.VolumeTypes = *(*[]string)(unsafe.Pointer(&in.VolumeTypes))
	out.MachineTypes = *(*[]string)(unsafe.Pointer(&in.MachineTypes))
	out.RootCerts = in.RootCerts
	out.LoadBalancerProvider = in.LoadBalancerProvider
	out.FloatingPoolName = in.FloatingPoolName
	return nil
}

// Convert_componentconfig_GardenOperatorCloudProviderConfiguration_To_v1alpha1_GardenOperatorCloudProviderConfiguration is an autogenerated conversion function.
func Convert_componentconfig_GardenOperatorCloudProviderConfiguration_To_v1alpha1_GardenOperatorCloudProviderConfiguration(in *componentconfig.GardenOperatorCloudProviderConfiguration, out *GardenOperatorCloudProviderConfiguration, s conversion.Scope) error {
	return autoConvert_componentconfig_GardenOperatorCloudProviderConfiguration_To_v1alpha1_GardenOperatorCloudProviderConfiguration(in, out, s)
}

func autoConvert_v1alpha1_GardenOperatorConfiguration_To_componentconfig_GardenOperatorConfiguration(in *GardenOperatorConfiguration, out *componentconfig.GardenOperatorConfiguration, s conversion.Scope) error {
	if err := Convert_v1alpha1_ClientConnectionConfiguration_To_componentconfig_ClientConnectionConfiguration(&in.ClientConnection, &out.ClientConnection, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_GardenOperatorControllerConfiguration_To_componentconfig_GardenOperatorControllerConfiguration(&in.Controller, &out.Controller, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_GardenConstraints_To_componentconfig_GardenConstraints(&in.Constraints, &out.Constraints, s); err != nil {
		return err
	}
	out.GardenNamespace = in.GardenNamespace
	out.Images = *(*[]componentconfig.GardenOperatorImagesConfiguration)(unsafe.Pointer(&in.Images))
	if err := Convert_v1alpha1_LeaderElectionConfiguration_To_componentconfig_LeaderElectionConfiguration(&in.LeaderElection, &out.LeaderElection, s); err != nil {
		return err
	}
	out.LogLevel = in.LogLevel
	if err := Convert_v1alpha1_ServerConfiguration_To_componentconfig_ServerConfiguration(&in.Server, &out.Server, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_GardenOperatorConfiguration_To_componentconfig_GardenOperatorConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_GardenOperatorConfiguration_To_componentconfig_GardenOperatorConfiguration(in *GardenOperatorConfiguration, out *componentconfig.GardenOperatorConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_GardenOperatorConfiguration_To_componentconfig_GardenOperatorConfiguration(in, out, s)
}

func autoConvert_componentconfig_GardenOperatorConfiguration_To_v1alpha1_GardenOperatorConfiguration(in *componentconfig.GardenOperatorConfiguration, out *GardenOperatorConfiguration, s conversion.Scope) error {
	if err := Convert_componentconfig_ClientConnectionConfiguration_To_v1alpha1_ClientConnectionConfiguration(&in.ClientConnection, &out.ClientConnection, s); err != nil {
		return err
	}
	if err := Convert_componentconfig_GardenOperatorControllerConfiguration_To_v1alpha1_GardenOperatorControllerConfiguration(&in.Controller, &out.Controller, s); err != nil {
		return err
	}
	if err := Convert_componentconfig_GardenConstraints_To_v1alpha1_GardenConstraints(&in.Constraints, &out.Constraints, s); err != nil {
		return err
	}
	out.GardenNamespace = in.GardenNamespace
	out.Images = *(*[]GardenOperatorImagesConfiguration)(unsafe.Pointer(&in.Images))
	if err := Convert_componentconfig_LeaderElectionConfiguration_To_v1alpha1_LeaderElectionConfiguration(&in.LeaderElection, &out.LeaderElection, s); err != nil {
		return err
	}
	out.LogLevel = in.LogLevel
	if err := Convert_componentconfig_ServerConfiguration_To_v1alpha1_ServerConfiguration(&in.Server, &out.Server, s); err != nil {
		return err
	}
	return nil
}

// Convert_componentconfig_GardenOperatorConfiguration_To_v1alpha1_GardenOperatorConfiguration is an autogenerated conversion function.
func Convert_componentconfig_GardenOperatorConfiguration_To_v1alpha1_GardenOperatorConfiguration(in *componentconfig.GardenOperatorConfiguration, out *GardenOperatorConfiguration, s conversion.Scope) error {
	return autoConvert_componentconfig_GardenOperatorConfiguration_To_v1alpha1_GardenOperatorConfiguration(in, out, s)
}

func autoConvert_v1alpha1_GardenOperatorControllerConfiguration_To_componentconfig_GardenOperatorControllerConfiguration(in *GardenOperatorControllerConfiguration, out *componentconfig.GardenOperatorControllerConfiguration, s conversion.Scope) error {
	out.HealthCheckPeriod = in.HealthCheckPeriod
	if err := Convert_v1alpha1_ControllerReconciliationConfiguration_To_componentconfig_ControllerReconciliationConfiguration(&in.Reconciliation, &out.Reconciliation, s); err != nil {
		return err
	}
	out.WatchNamespace = (*string)(unsafe.Pointer(in.WatchNamespace))
	return nil
}

// Convert_v1alpha1_GardenOperatorControllerConfiguration_To_componentconfig_GardenOperatorControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_GardenOperatorControllerConfiguration_To_componentconfig_GardenOperatorControllerConfiguration(in *GardenOperatorControllerConfiguration, out *componentconfig.GardenOperatorControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_GardenOperatorControllerConfiguration_To_componentconfig_GardenOperatorControllerConfiguration(in, out, s)
}

func autoConvert_componentconfig_GardenOperatorControllerConfiguration_To_v1alpha1_GardenOperatorControllerConfiguration(in *componentconfig.GardenOperatorControllerConfiguration, out *GardenOperatorControllerConfiguration, s conversion.Scope) error {
	out.HealthCheckPeriod = in.HealthCheckPeriod
	if err := Convert_componentconfig_ControllerReconciliationConfiguration_To_v1alpha1_ControllerReconciliationConfiguration(&in.Reconciliation, &out.Reconciliation, s); err != nil {
		return err
	}
	out.WatchNamespace = (*string)(unsafe.Pointer(in.WatchNamespace))
	return nil
}

// Convert_componentconfig_GardenOperatorControllerConfiguration_To_v1alpha1_GardenOperatorControllerConfiguration is an autogenerated conversion function.
func Convert_componentconfig_GardenOperatorControllerConfiguration_To_v1alpha1_GardenOperatorControllerConfiguration(in *componentconfig.GardenOperatorControllerConfiguration, out *GardenOperatorControllerConfiguration, s conversion.Scope) error {
	return autoConvert_componentconfig_GardenOperatorControllerConfiguration_To_v1alpha1_GardenOperatorControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_GardenOperatorImagesConfiguration_To_componentconfig_GardenOperatorImagesConfiguration(in *GardenOperatorImagesConfiguration, out *componentconfig.GardenOperatorImagesConfiguration, s conversion.Scope) error {
	out.Name = in.Name
	out.Image = in.Image
	return nil
}

// Convert_v1alpha1_GardenOperatorImagesConfiguration_To_componentconfig_GardenOperatorImagesConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_GardenOperatorImagesConfiguration_To_componentconfig_GardenOperatorImagesConfiguration(in *GardenOperatorImagesConfiguration, out *componentconfig.GardenOperatorImagesConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_GardenOperatorImagesConfiguration_To_componentconfig_GardenOperatorImagesConfiguration(in, out, s)
}

func autoConvert_componentconfig_GardenOperatorImagesConfiguration_To_v1alpha1_GardenOperatorImagesConfiguration(in *componentconfig.GardenOperatorImagesConfiguration, out *GardenOperatorImagesConfiguration, s conversion.Scope) error {
	out.Name = in.Name
	out.Image = in.Image
	return nil
}

// Convert_componentconfig_GardenOperatorImagesConfiguration_To_v1alpha1_GardenOperatorImagesConfiguration is an autogenerated conversion function.
func Convert_componentconfig_GardenOperatorImagesConfiguration_To_v1alpha1_GardenOperatorImagesConfiguration(in *componentconfig.GardenOperatorImagesConfiguration, out *GardenOperatorImagesConfiguration, s conversion.Scope) error {
	return autoConvert_componentconfig_GardenOperatorImagesConfiguration_To_v1alpha1_GardenOperatorImagesConfiguration(in, out, s)
}

func autoConvert_v1alpha1_LeaderElectionConfiguration_To_componentconfig_LeaderElectionConfiguration(in *LeaderElectionConfiguration, out *componentconfig.LeaderElectionConfiguration, s conversion.Scope) error {
	out.LeaderElect = in.LeaderElect
	out.LeaseDuration = in.LeaseDuration
	out.RenewDeadline = in.RenewDeadline
	out.RetryPeriod = in.RetryPeriod
	out.ResourceLock = in.ResourceLock
	out.LockObjectNamespace = in.LockObjectNamespace
	out.LockObjectName = in.LockObjectName
	return nil
}

// Convert_v1alpha1_LeaderElectionConfiguration_To_componentconfig_LeaderElectionConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_LeaderElectionConfiguration_To_componentconfig_LeaderElectionConfiguration(in *LeaderElectionConfiguration, out *componentconfig.LeaderElectionConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_LeaderElectionConfiguration_To_componentconfig_LeaderElectionConfiguration(in, out, s)
}

func autoConvert_componentconfig_LeaderElectionConfiguration_To_v1alpha1_LeaderElectionConfiguration(in *componentconfig.LeaderElectionConfiguration, out *LeaderElectionConfiguration, s conversion.Scope) error {
	out.LeaderElect = in.LeaderElect
	out.LeaseDuration = in.LeaseDuration
	out.RenewDeadline = in.RenewDeadline
	out.RetryPeriod = in.RetryPeriod
	out.ResourceLock = in.ResourceLock
	out.LockObjectNamespace = in.LockObjectNamespace
	out.LockObjectName = in.LockObjectName
	return nil
}

// Convert_componentconfig_LeaderElectionConfiguration_To_v1alpha1_LeaderElectionConfiguration is an autogenerated conversion function.
func Convert_componentconfig_LeaderElectionConfiguration_To_v1alpha1_LeaderElectionConfiguration(in *componentconfig.LeaderElectionConfiguration, out *LeaderElectionConfiguration, s conversion.Scope) error {
	return autoConvert_componentconfig_LeaderElectionConfiguration_To_v1alpha1_LeaderElectionConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ServerConfiguration_To_componentconfig_ServerConfiguration(in *ServerConfiguration, out *componentconfig.ServerConfiguration, s conversion.Scope) error {
	out.BindAddress = in.BindAddress
	out.Port = in.Port
	return nil
}

// Convert_v1alpha1_ServerConfiguration_To_componentconfig_ServerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ServerConfiguration_To_componentconfig_ServerConfiguration(in *ServerConfiguration, out *componentconfig.ServerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServerConfiguration_To_componentconfig_ServerConfiguration(in, out, s)
}

func autoConvert_componentconfig_ServerConfiguration_To_v1alpha1_ServerConfiguration(in *componentconfig.ServerConfiguration, out *ServerConfiguration, s conversion.Scope) error {
	out.BindAddress = in.BindAddress
	out.Port = in.Port
	return nil
}

// Convert_componentconfig_ServerConfiguration_To_v1alpha1_ServerConfiguration is an autogenerated conversion function.
func Convert_componentconfig_ServerConfiguration_To_v1alpha1_ServerConfiguration(in *componentconfig.ServerConfiguration, out *ServerConfiguration, s conversion.Scope) error {
	return autoConvert_componentconfig_ServerConfiguration_To_v1alpha1_ServerConfiguration(in, out, s)
}
