#!/usr/bin/env sh

set -e

# Env variables passed from pipeline task 
# SOURCE_PATH
# VERSION_PATH
# BINARY_PATH

if [ ! -z "$SOURCE_PATH" ]; then
  export SRC_DIR="${SOURCE_PATH}"
else
  own_dir="$(dirname $(readlink -f ${0}))"
  export SRC_DIR="${own_dir}/.."
fi
export SRC_DIR="$(readlink -f "${SRC_DIR}")"

export VERSION_FILE="$(readlink -f "${SRC_DIR}/VERSION")"
export VERSION="$(cat "${VERSION_FILE}")"

if [ ! -z "$BINARY_PATH" ]; then
  export BIN_PATH="${BINARY_PATH}"
else
  export BIN_PATH="${SRC_DIR}"
fi
export BIN_PATH="$(readlink -f "${BIN_PATH}")"

export OUT_DIR="$(readlink -f "${BIN_PATH}")/bin/rel"

echo "SRC_DIR: ${SRC_DIR}"
echo "OUT_DIR: ${OUT_DIR}"
echo "VERSION: ${VERSION}"

export GOPATH="${SRC_DIR}"
mkdir -p "${SRC_DIR}/src/github.com/gardener"
src_symlink="${SRC_DIR}/src/github.com/gardener/gardenctl"
if [ -s "${src_symlink}" ]; then
  rm "${src_symlink}"
fi
ln -s "${SRC_DIR}" "${src_symlink}"
cd "${src_symlink}"

set -x
go build -o ${OUT_DIR}/gardenctl gardenctl.go




