#!/usr/bin/env bash

set -xeo pipefail

# For the test step concourse will set the following environment variables:
# SOURCE_PATH - path to component repository root directory.

if [[ -z "${SOURCE_PATH}" ]]; then
  export SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"
else
  export SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi

cd "${SOURCE_PATH}"

# Ensure Ginkgo (test framework) is installed
if ! go list github.com/onsi/ginkgo > /dev/null 2>&1 ; then
  go install -mod=vendor ./vendor/github.com/onsi/ginkgo/ginkgo
fi

ginkgo -v -progress -cover -r -mod=vendor pkg/..
