#!/usr/bin/env bash

set -e

# For the test step concourse will set the following environment variables:
# SOURCE_PATH - path to component repository root directory.

if [[ -z "${SOURCE_PATH}" ]]; then
  export SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"
else
  export SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi

cd "${SOURCE_PATH}"


# Build the Ginkgo (test framework) binary to be able to execute the tests.
go install -mod=vendor ./vendor/github.com/onsi/ginkgo/ginkgo

###############################################################################

ginkgo -v -progress -cover -r -mod=vendor pkg/...




