#!/usr/bin/env bash

set -xeo pipefail

gardener_project="gardenctl"
shoot_namespace="garden-${gardener_project}"
gardener_url="https://gardener.garden.dev.k8s.ondemand.com"
gardenctl_cmd=( "go" "run" "cmd/gardenctl/main.go" )


# SOURCE_PATH - path to component repository root directory.
if [[ -z "${SOURCE_PATH}" ]]; then
  export SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"
else
  export SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi

gardenctl_ssh() {
  shoot_name="${1}"
  cd "${SOURCE_PATH}"

  # Target the garden to wake the shoot
  "${gardenctl_cmd[@]}" target garden dev
  "${gardenctl_cmd[@]}" kubectl patch shoot "${shoot_name}" -n "${shoot_namespace}" -p '{"spec":{"hibernation":{"enabled":false}}}'

  # Wait for shoot to wake
  while [[ $("${gardenctl_cmd[@]}" kubectl get shoot "${shoot_name}" -n "${shoot_namespace}" | awk -v i=2 -v j=6 'FNR == i {print $j}') != "Awake" ]]; do
    echo 'Waiting for the cluster to wake up...'
    sleep 5
  done

  # Target the shoot to ssh
  "${gardenctl_cmd[@]}" target --server "${gardener_url}" --project "${gardener_project}" --shoot "${shoot_name}"
  node_name=$("${gardenctl_cmd[@]}" kubectl get node -o name | awk -F'/' '{print $2}')
  "${gardenctl_cmd[@]}" ssh "${node_name}" exit
}

# gardenctl_ssh gctl-gcp
gardenctl_ssh gctl-aws
# gardenctl_ssh gctl-az
# gardenctl_ssh gctl-os

